### ISSUE TITLE
Select database error in the newly relased version 2.0.1

### ISSUE THREAD

**Issue by seunex17** [irsyadulibad/ci4-datatables#20]
I am having this error:

```
ERROR - 2022-03-21 04:54:00 --> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 7
CRITICAL - 2022-03-21 04:54:00 --> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ')' at line 7
#0 C:\xampp\htdocs\clients\wiafrica_ads\wa_codes\vendor\codeigniter4\framework\system\Database\MySQLi\Connection.php(292): mysqli->query('SELECT COUNT(*)...', 0)
#1 C:\xampp\htdocs\clients\wiafrica_ads\wa_codes\vendor\codeigniter4\framework\system\Database\BaseConnection.php(670): CodeIgniter\Database\MySQLi\Connection->execute('SELECT COUNT(*)...')
#2 C:\xampp\htdocs\clients\wiafrica_ads\wa_codes\vendor\codeigniter4\framework\system\Database\BaseConnection.php(598): CodeIgniter\Database\BaseConnection->simpleQuery('SELECT COUNT(*)...')
#3 C:\xampp\htdocs\clients\wiafrica_ads\wa_codes\vendor\codeigniter4\framework\system\Database\BaseBuilder.php(1539): CodeIgniter\Database\BaseConnection->query('SELECT COUNT(*)...', Array, false)
#4 C:\xampp\htdocs\clients\wiafrica_ads\wa_codes\vendor\irsyadulibad\codeigniter4-datatables\src\DataTableAbstract.php(186): CodeIgniter\Database\BaseBuilder->countAllResults(false)
#5 C:\xampp\htdocs\clients\wiafrica_ads\wa_codes\vendor\irsyadulibad\codeigniter4-datatables\src\DataTableAbstract.php(195): Irsyadulibad\DataTables\DataTableAbstract->countTotal()
#6 C:\xampp\htdocs\clients\wiafrica_ads\wa_codes\vendor\irsyadulibad\codeigniter4-datatables\src\QueryDataTable.php(34): Irsyadulibad\DataTables\DataTableAbstract->countFiltered()
#7 C:\xampp\htdocs\clients\wiafrica_ads\wa_codes\vendor\irsyadulibad\codeigniter4-datatables\src\QueryDataTable.php(24): Irsyadulibad\DataTables\QueryDataTable->execQueries()
#8 C:\xampp\htdocs\clients\wiafrica_ads\wa_codes\app\Controllers\Admin\AccountController.php(89): Irsyadulibad\DataTables\QueryDataTable->make(true)
#9 C:\xampp\htdocs\clients\wiafrica_ads\wa_codes\vendor\codeigniter4\framework\system\CodeIgniter.php(832): App\Controllers\Admin\AccountController->manageAccounts('admin')
#10 C:\xampp\htdocs\clients\wiafrica_ads\wa_codes\vendor\codeigniter4\framework\system\CodeIgniter.php(419): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Admin\AccountController))
#11 C:\xampp\htdocs\clients\wiafrica_ads\wa_codes\vendor\codeigniter4\framework\system\CodeIgniter.php(326): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 C:\xampp\htdocs\clients\wiafrica_ads\wa_codes\public\index.php(37): CodeIgniter\CodeIgniter->run()
#13 C:\xampp\htdocs\clients\wiafrica_ads\wa_codes\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(43): require_once('C:\\xampp\\htdocs...')
#14 {main}
```

**Comment by irsyadulibad** [comment]
Your problem is fixed at #21
